name: vulcan-root-snowflake
display_name: Root Snowflake Data Product
tenant: qa
description: Snowflake analytics on SNOWFLAKE_SAMPLE_DATA.TPCH_SF1 using depot-based connection.

tags:
  - snowflake
  - production
  - depot

users:
  - username: anushkarakeshtmdcio
    email: anushka.rakesh@tmdc.io
    type: OWNER

linter:
  enabled: true

gateways:
  default:
    connection:
      type: depot
      address: dataos://snowflakevulcan

model_defaults:
  dialect: snowflake
  cron: "@daily"
